#!/bin/bash

#This script is for the intended purpose of giving a full system report

echo
echo -n 'System Report generated by' "$USER"', ' ; uptime | awk '{print $1}'
echo
echo 'System Information'
echo '------------------'
echo 'HOSTNAME: ' "$HOSTNAME"
echo -n 'OS: ' ; hostnamectl | grep -E 'Operating System:' | awk '/Operating System:/ {print $3, $4, $5}'
echo -n 'UPTIME: ' ; uptime -p | sed 's/up//'
echo
echo 'Hardware Information'
echo '--------------------'
echo -n 'CPU: ' ;  lscpu | grep -E '^Model name' | awk '{print $3, $4, $5, $6, $7, $8, $9}'
echo -n 'RAM: ' ; sudo cat /proc/meminfo | grep -E '^MemTotal' | awk '{print $2, $3}'
