#!/bin/bash

#This script is for the intended purpose of giving a full system report

#Echo used alone for spaceing purposes
#Using -n to keep outputs on the same line and ; to have more then one output on the same line
#This first part here gives the current user using $USER to grab the cureent user  and uses date to print the date and time
echo
echo -n 'System Report generated by' "$USER"', ' ; date
echo
#This is the system information section
#I do the same thing as $USER to get HOSTNAME, using $HOSTNAME. Needs ti be all caps
#For OS I use hostnameclt and well as grep -E, -E to make it more flexible in its serach. Then use awk to print out only the distro's name and version
#Uptime using uptime -p to only give the uptime without the extra fluff. Used sed to get rid of up to make it look cleaner 
echo 'System Information'
echo '------------------'
echo 'HOSTNAME: ' "$HOSTNAME"
echo -n 'OS: ' ; hostnamectl | grep -E 'Operating System:' | awk '/Operating System:/ {print $3, $4, $5}'
echo -n 'UPTIME: ' ; uptime -p | sed 's/up//'
echo
#This is the hardware information section. Comments to each line filled whenever I get around to it
#I'm too tired rn to write it. Will do tomorrow
#But is done now. This part at least
#
#
echo 'Hardware Information'
echo '--------------------'
echo -n 'CPU: ' ;  lscpu | grep -E '^Model name' | awk -F ':' '{print $2}' | sed 's/^[[:space:]]*//' 
echo -n 'RAM: ' ; free -h | grep -E '^Mem:' | awk '{print $2}'
echo 'DISK(S): ' ; lsblk -o NAME,SIZE,MODEL | grep -v loop
echo -n 'VIDEO: ' ; lspci | grep -i VGA | awk -F ':' '{print $3}' 
echo
#
#
#
#
#
echo 'Network Information'
echo '-------------------'

